#!/usr/bin/env bash
# Bash script to configure Nginx for a 301 Moved Permanently redirection

sudo apt-get update
sudo apt-get install -y nginx

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
sudo service nginx start
