#!/usr/bin/env bash
# Script Description: Configure Nginx with custom HTTP response header on a new Ubuntu machine.
# Install Nginx
# Create a custom Nginx configuration file
# Remove the default Nginx welcome page
# Restart Nginx to apply changes

sudo apt-get update
sudo apt-get install -y nginx
#sudo wget -q -O /etc/nginx/sites-available/default http://exampleconfig.com/static/raw/nginx/ubuntu20.04/etc/nginx/sites-available/default
config="/etc/nginx/sites-available/default"
sudo sh -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' $config
sudo sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' $config
sudo sed -i 's/=404/@404/g' $config
sudo sed -i "0,/location \/ {/s/location \/ {/&\n\t\tadd_header X-Served-By '$HOSTNAME';/" $config
sudo service nginx restart
