#!/usr/bin/env bash
# Script Description: Install and configure HAproxy on a new Ubuntu machine.
# Install HAproxy
# Configure HAproxy
# Enable HAproxy init script
# Restart HAproxy to apply changes

sudo apt-get -y update
sudo apt-get install -y haproxy

server_config=\
"
frontend  medchakir
        bind *:80
        mode http
        default_backend medchakir
backend medchakir
        balance roundrobin
        server 63210-web-01 54.237.26.209:80 check
        server 63210-web-02 34.229.137.28:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
