#!/usr/bin/env bash
# Troubleshooting Nginx: The service initializer should indicate that Nginx is not running.
apt-get update
apt-get install -y nginx
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
