#!/usr/bin/env bash
# Script to display username, user id, and home directory path from /etc/passwd

while IFS=: read -r username _ uid _ _ home _;
do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
