#!/usr/bin/env bash
# Script to loop from 1 to 10 with specific messages on certain iterations

counter=1

while [ $counter -le 10 ];
do
    if [ $counter -eq 4 ]; then
        echo "Bad Luck"
    elif [ $counter -eq 8 ]; then
        echo "Good Luck"
    else
        echo "Best School"
    fi

    ((counter++))
done
