#!/usr/bin/env bash
# Displays the time for 12 hrs and 59 mins.
# Displays hours fm 0 to 12
# Displays minutes fm 1 to 59

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
