#!/usr/bin/env bash
# Script to display the content of the current directory in a specific format

for file in *;
do
    if [ -f "$file" ]; then
        display_name=$(echo "$file" | cut -d'-' -f2-)

        echo "$display_name"
    fi
done
